sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=cisagov/saver
    - DOCKER_USER=jsf9k
    - secure: "KOBnF822WhgariMvzbFLZYozGUCA/Khc9HVc8jGr6l9k0aiA/8udPc62LNRfWeOzDbs7dIRdorrw8DxtMMXwdaO2eo3OfYodkhwKLJSwYPXyeZO2ossYSyojC1I9f67YqkatUPNnGqd/OwRtxUCnHlIqDZ1SLlNKAkzdtj2HLj9pYvNOCA9ow7XQxhvWijuQ+dJehlACrI2eXHwf3XuDsJSzhQzJkyFAtgyCZ0EkZiyaz9BCldKWeJwO7PHQX0RMPd9vzm5aPTM6192OH99MP/NB43PcK8W2twA03jbCzW4+F8WV+lfpHqsZLk1XKQz4IkTSFXjB7IMSSoqWE/XcD6/Q4l6uodiaM1yzfod6nE/lDMxY76hKilgM4LvEaI/dMAreqhd8Zmsts1nVYms5fY3/0Zegk2d9IsePaj/Vqe0sartPqqYxDDpCN/NVbCkB+2j71K1DtHHyRez8Etbmpuk8r50sIeYzCc2qAWf+ll9VBa6jb+tw5d37JOjlfh+js5bnYG5jU98ZgZ1+uQD3i427XM4vODqxaQ9ppQwYm7EwiOn4VB+cZcaWsuaB0X/fGfJRNU/w/ovAKasW5ONRfuWlyLuoza6Issy9VvwmA8PdwQ8df4aWM3ZhUMWNL9oWESMq6GbK57uNwl0U0WsrbNcgudJ+cbLjNUZy119Z3jI="

script:
  - bash travis_scripts/build_docker_image.sh

deploy:
  - provider: script
    script: bash travis_scripts/deploy_to_docker_hub.sh
    on:
      tags: true
